spring:
  application:
    name: users
  config:
    import: "optional:configserver:"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:postgresql://localhost:5432/app_db?options=-c%20TimeZone=UTC
    username: app_user
    password: app_pass
    driver-class-name: org.postgresql.Driver

jpa:
  hibernate:
    ddl-auto: validate   # update SOLO para dev
  show-sql: true
  properties:
    hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

